# Generated by Django 5.2.4 on 2025-07-10 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Citation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        unique=True,
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                ("source", models.CharField(max_length=255)),
                ("weight", models.PositiveIntegerField(default=1)),
                ("likes", models.PositiveIntegerField(db_index=True, default=0)),
                ("dislikes", models.PositiveIntegerField(default=0)),
                ("views", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("likes",),
            },
        ),
    ]
