# Generated by Django 5.2.4 on 2025-07-10 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citation",
            name="text",
            field=models.TextField(
                db_index=True,
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(2000)],
            ),
        ),
    ]
